Load image after build as cache validation
Signed-off-by: Miroslav Kovar <miroslavkovar@protonmail.com>

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -8,13 +8,12 @@ jobs:
     outputs:
       GITHUB_REPOSITORY_LOWERCASE: ${{ steps.mainstep.outputs.GITHUB_REPOSITORY_LOWERCASE }}
       BRANCH_NAME: ${{ steps.mainstep.outputs.BRANCH_NAME }}
-      DOCKER_TAG_VERSION: ${{ steps.mainstep.outputs.DOCKER_TAG_VERSION }}
       RELEASE_VERSION: ${{ steps.mainstep.outputs.RELEASE_VERSION }}
       CACHE_KEY_AGENCY: ${{ steps.mainstep.outputs.CACHE_KEY_AGENCY }}
       CACHE_KEY_LIBVCX: ${{ steps.mainstep.outputs.CACHE_KEY_LIBVCX }}
       CACHE_KEY_POOL: ${{ steps.mainstep.outputs.CACHE_KEY_POOL }}
       DOCKER_IMG_NAME_POOL: ${{ steps.mainstep.outputs.DOCKER_IMG_NAME_POOL }}
-      DOCKER_IMG_NAME_AGENCY: "docker.pkg.github.com/absaoss/vcxagencynode/vcxagency-node:0.1.0"
+      DOCKER_IMG_NAME_AGENCY: ${{ steps.mainstep.outputs.DOCKER_IMG_NAME_AGENCY }}
       DOCKER_IMG_NAME_LIBVCX: ${{ steps.mainstep.outputs.DOCKER_IMG_NAME_LIBVCX }}
     steps:
       - run: echo $GITHUB_REPOSITORY
@@ -44,17 +43,11 @@ jobs:
 
           BRANCH_NAME=`echo $BRANCH_NAME | sed "s/[^[:alnum:]-]//g" | tr '[:upper:]' '[:lower:]'` # lowercase, only alphanumeric and dash
           echo ::set-env name=BRANCH_NAME::$(echo $BRANCH_NAME)
-
-          DOCKER_TAG_VERSION="$BRANCH_NAME"
-
-          echo ::set-env name=DOCKER_TAG_VERSION::$(echo $DOCKER_TAG_VERSION)
-          echo "Docker images built in this CI will be using tag '$DOCKER_TAG_VERSION'"
-
-          echo ::set-env name=DOCKER_TAG_VERSION::$(echo $DOCKER_TAG_VERSION)
-
-          echo ::set-env name=AGENCY_CACHE::$(echo ${{ hashFiles('agency.Dockerfile') }})
           echo ::set-env name=LIBVCX_HASH::$(echo ${{ hashFiles('libvcx') }})
           echo ::set-env name=POOL_HASH::$(echo ${{ hashFiles('indy-pool.dockerfile') }})
+
+          DOCKER_IMG_NAME_AGENCY="docker.pkg.github.com/absaoss/vcxagencynode/vcxagency-node:0.1.0"
+          echo ::set-env name=DOCKER_IMG_NAME_AGENCY::$(echo $DOCKER_IMG_NAME_AGENCY)
 
       - name: Set and print outputs
         id: mainstep
@@ -62,13 +55,12 @@ jobs:
           set -x
           echo "::set-output name=GITHUB_REPOSITORY_LOWERCASE::$GITHUB_REPOSITORY_LOWERCASE"
           echo "::set-output name=BRANCH_NAME::$BRANCH_NAME"
-          echo "::set-output name=DOCKER_TAG_VERSION::$DOCKER_TAG_VERSION"
           echo "::set-output name=CACHE_KEY_AGENCY::$DOCKER_IMG_NAME_AGENCY"
-          echo "::set-output name=CACHE_KEY_LIBVCX::$(echo reposlug-$FULL_REPO_SLUG-branch-$BRANCH_NAME-hash-$LIBVCX_HASH)"
-          echo "::set-output name=CACHE_KEY_POOL::$(echo reposlug-$FULL_REPO_SLUG-branch-$BRANCH_NAME-hash-$POOL_HASH)"
+          echo "::set-output name=CACHE_KEY_LIBVCX::$(echo branch-$BRANCH_NAME-hash-$LIBVCX_HASH)"
+          echo "::set-output name=CACHE_KEY_POOL::$(echo branch-$BRANCH_NAME-hash-$POOL_HASH)"
           echo "::set-output name=DOCKER_IMG_NAME_AGENCY::$DOCKER_IMG_NAME_AGENCY"
-          echo "::set-output name=DOCKER_IMG_NAME_LIBVCX::libvcx:$DOCKER_TAG_VERSION"
-          echo "::set-output name=DOCKER_IMG_NAME_POOL::indypool:$DOCKER_TAG_VERSION"
+          echo "::set-output name=DOCKER_IMG_NAME_LIBVCX::libvcx:$BRANCH_NAME"
+          echo "::set-output name=DOCKER_IMG_NAME_POOL::indypool:$BRANCH_NAME"
 
 
   build-image-indypool:
@@ -99,6 +91,13 @@ jobs:
                         .
           mkdir -p /tmp/imgcache
           docker save "$DOCKER_IMG_NAME_POOL" > /tmp/imgcache/img_indypool.rar
+
+      - name: Load pool image from cache
+        run: |
+          docker load < /tmp/imgcache/img_indypool.rar
+      - name: Verify indypool image was loaded
+        run: |
+          docker image ls --format "{{.Repository}}:{{.Tag}}" | grep "$DOCKER_IMG_NAME_POOL" || { echo "Image $DOCKER_IMG_NAME_POOL was not found!" ; exit 1; }
 
 #  build-image-ubuntu16-libindy:
 #    needs:
@@ -141,6 +140,10 @@ jobs:
     env:
       DOCKER_BUILDKIT: 1
     steps:
+      - name: Load up custom variables
+        run: |
+          echo ::set-env name=CACHE_KEY_AGENCY::$(echo ${{needs.workflow-setup.outputs.CACHE_KEY_AGENCY}})
+          echo ::set-env name=DOCKER_IMG_NAME_AGENCY::$(echo ${{needs.workflow-setup.outputs.DOCKER_IMG_NAME_AGENCY}})
       - name: Git checkout
         uses: actions/checkout@v2
       - name: Login to docker
@@ -154,7 +157,7 @@ jobs:
         uses: actions/cache@v2
         with:
           path: /tmp/imgcache
-          key: $DOCKER_IMG_NAME_AGENCY
+          key: ${{ env.CACHE_KEY_AGENCY }}
       - name: If no cached image found, pull and save to cache
         if: steps.load-cached-image-node.outputs.cache-hit != 'true'
         run: |
@@ -162,6 +165,14 @@ jobs:
           docker pull $DOCKER_IMG_NAME_AGENCY
           mkdir -p /tmp/imgcache
           docker save "$DOCKER_IMG_NAME_AGENCY" > /tmp/imgcache/img_agency.rar
+
+      - name: Load agency image from cache
+        run: |
+          docker load < /tmp/imgcache/img_agency.rar
+      - name: Verify agency image was loaded
+        run: |
+          docker image ls --format "{{.Repository}}:{{.Tag}}" | grep "$DOCKER_IMG_NAME_AGENCY" || { echo "Image $DOCKER_IMG_NAME_AGENCY was not found!" ; exit 1; }
+
 
   build-image-libvcx:
     needs:
@@ -195,6 +206,14 @@ jobs:
                         .
           mkdir -p /tmp/imgcache
           docker save "$DOCKER_IMG_NAME_LIBVCX" > /tmp/imgcache/img_libvcx.rar
+
+      - name: Load libvcx image from cache
+        run: |
+          docker load < /tmp/imgcache/img_libvcx.rar
+      - name: Verify agency image was loaded
+        run: |
+          docker image ls --format "{{.Repository}}:{{.Tag}}" | grep "$DOCKER_IMG_NAME_LIBVCX" || { echo "Image $DOCKER_IMG_NAME_LIBVCX was not found!" ; exit 1; }
+
 
 #
 #  #
@@ -253,7 +272,7 @@ jobs:
           key: ${{ env.CACHE_KEY_LIBVCX }}
       - name: If no cached image found
         if: steps.load-cached-libvcx-image.outputs.cache-hit != 'true'
-        run: echo "ERROR == Expected to find image from cache $CACHE_KEY_AGENCY"; exit -1
+        run: echo "ERROR == Expected to find image from cache $CACHE_KEY_LIBVCX"; exit -1
       - name: Load pool image from cache
         run: docker load < /tmp/imgcache/img_libvcx.rar
 
