Publish wrapper
Signed-off-by: Miroslav Kovar <miroslavkovar@protonmail.com>

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -107,7 +107,6 @@ jobs:
           echo "::set-output name=DOCKER_IMG_NAME_AGENCY::$DOCKER_IMG_NAME_AGENCY"
           echo "::set-output name=DOCKER_IMG_NAME_LIBVCX::libvcx:$DOCKER_TAG_VERSION"
           echo "::set-output name=DOCKER_IMG_NAME_POOL::indypool:$DOCKER_TAG_VERSION"
-          echo "::set-output name=NPM_PKG_NAME_NODE_WRAPPER::node-vcx-wrapper:$DOCKER_TAG_VERSION"
 
 
   build-image-indypool:
@@ -214,6 +213,7 @@ jobs:
                        --build-arg "INDYSDK_REVISION=v$INDYSDK_REVISION" \
                        --build-arg "RUST_VER=$RUST_VER" \
                        --build-arg "NODE_VER=$NODE_VER" \
+                       --build-arg "NPMJS_TOKEN=$NPMJS_TOKEN" \
                        -f ci/libvcx.dockerfile \
                        -t "$DOCKER_IMG_NAME_LIBVCX" \
                         .
@@ -370,24 +370,70 @@ jobs:
       - name: Docker Login
         uses: azure/docker-login@v1
         with:
-          login-server: docker.pkg.github.com # TODO: Temporarily, publish to GPR
+          login-server: docker.pkg.github.com
           username: $GITHUB_ACTOR
           password: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Publish image
         run: |
-          REMOTE_DOCKER_IMG_NAME_LIBVCX="docker.pkg.github.com/$GITHUB_REPOSITORY_LOWERCASE/$DOCKER_IMG_NAME_LIBVCX"
-          docker tag "$DOCKER_IMG_NAME_LIBVCX" "$REMOTE_DOCKER_IMG_NAME_LIBVCX"
-          docker push "$REMOTE_DOCKER_IMG_NAME_LIBVCX" || true
+          if [[ "$RELEASE_VERSION" ]]
+          then
+            echo "Releasing libvcx docker image version $RELEASE_VERSION..."
+            REMOTE_DOCKER_IMG_NAME_LIBVCX="docker.pkg.github.com/$GITHUB_REPOSITORY_LOWERCASE/$DOCKER_IMG_NAME_LIBVCX"
+            docker tag "$DOCKER_IMG_NAME_LIBVCX" "$REMOTE_DOCKER_IMG_NAME_LIBVCX"
+            docker push "$REMOTE_DOCKER_IMG_NAME_LIBVCX" || true
+          else
+             echo "New version was not defined, skipping release.'workflow-setup' job to see the reason."
+          fi
 
-#   publish-node-wrapper:
-#     runs-on: ubuntu-16.04
-#     needs: [workflow-setup, build-image-indypool, build-image-libvcx, build-image-vcxagency, test-libvcx, test-node-wrapper]
-#     steps:
-#       - name: Load env. variables
-#         run: |
-#           echo ::set-env name=NPM_PKG_NAME_NODE_WRAPPER::$(echo ${{needs.workflow-setup.outputs.NPM_PKG_NAME_NODE_WRAPPER}})
-#           echo ::set-env name=GITHUB_REPOSITORY_LOWERCASE::$(echo ${{needs.workflow-setup.outputs.GITHUB_REPOSITORY_LOWERCASE}})
-# 
-#       - name: Git checkout
-#         uses: actions/checkout@v2
+  publish-node-wrapper:
+    runs-on: ubuntu-16.04
+    needs: [workflow-setup, build-image-indypool, build-image-libvcx, build-image-vcxagency, test-libvcx, test-node-wrapper]
+    env:
+      NPMJS_TOKEN: ${{ secrets.NPMJS_TOKEN }}
+    steps:
+      - name: Load env. variables
+        run: |
+          echo ::set-env name=CACHE_KEY_LIBVCX::$(echo ${{needs.workflow-setup.outputs.CACHE_KEY_LIBVCX}})
+          echo ::set-env name=DOCKER_IMG_NAME_LIBVCX::$(echo ${{needs.workflow-setup.outputs.DOCKER_IMG_NAME_LIBVCX}})
+      - name: Git checkout
+        uses: actions/checkout@v2
+
+      - name: Load libvcx image cache
+        id: load-cached-libvcx-image
+        uses: actions/cache@v2
+        with:
+          path: /tmp/imgcache
+          key: ${{ env.CACHE_KEY_LIBVCX }}
+      - name: If no cached image found
+        if: steps.load-cached-libvcx-image.outputs.cache-hit != 'true'
+        run: echo "ERROR == Expected to find image from cache $CACHE_KEY_LIBVCX"; exit -1
+      - name: Load image from cache
+        run: docker load < /tmp/imgcache/img_libvcx.rar
+
+      - name: Verify images were loaded
+        run: |
+          docker image ls --format "{{.Repository}}:{{.Tag}}" | grep "$DOCKER_IMG_NAME_LIBVCX" || { echo "Image $DOCKER_IMG_NAME_LIBVCX was not found!"; docker image ls; exit 1; }
+
+      - name: Docker Login
+        uses: azure/docker-login@v1
+        with:
+          login-server: docker.pkg.github.com
+          username: $GITHUB_ACTOR
+          password: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Release wrapper
+        run: |
+          if [[ "$RELEASE_VERSION" ]]
+          then
+            echo "Releasing node wrapper version $RELEASE_VERSION..."
+            docker run --rm -i --name libvcx --network host -e NPMJS_TOKEN=$NPMJS_TOKEN -e RELEASE_VERSION=$RELEASE_VERSION $DOCKER_IMG_NAME_LIBVCX \
+                                bash -c '(
+                                  cd $HOME/wrappers/node && \
+                                  npm install && \
+                                  npm run compile && \
+                                  npm version $RELEASE_VERSION && \
+                                  npm publish)'
+          else
+             echo "New version was not defined, skipping release.'workflow-setup' job to see the reason."
+          fi
