Add libvcx publish
Signed-off-by: Miroslav Kovar <miroslavkovar@protonmail.com>

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -324,4 +324,46 @@ jobs:
                                 cd $HOME/wrappers/node && \
                                 npm install && \
                                 npm run compile && \
-                                npm test)' 
+                                npm test)'
+    
+  publish-libvcx:
+    runs-on: ubuntu-16.04
+    needs: [workflow-setup, build-image-indypool, build-image-libvcx, build-image-vcxagency, test-libvcx]
+    steps:
+      - name: Load env. variables
+        run: |
+          echo ::set-env name=CACHE_KEY_LIBVCX::$(echo ${{needs.workflow-setup.outputs.CACHE_KEY_LIBVCX}})
+          echo ::set-env name=DOCKER_IMG_NAME_LIBVCX::$(echo ${{needs.workflow-setup.outputs.DOCKER_IMG_NAME_LIBVCX}})
+          echo ::set-env name=GITHUB_REPOSITORY_LOWERCASE::$(echo ${{needs.workflow-setup.outputs.GITHUB_REPOSITORY_LOWERCASE}})
+
+      - name: Git checkout
+        uses: actions/checkout@v2
+
+      - name: Load libvcx image cache
+        id: load-cached-libvcx-image
+        uses: actions/cache@v2
+        with:
+          path: /tmp/imgcache
+          key: ${{ env.CACHE_KEY_LIBVCX }}
+      - name: If no cached image found
+        if: steps.load-cached-libvcx-image.outputs.cache-hit != 'true'
+        run: echo "ERROR == Expected to find image from cache $CACHE_KEY_LIBVCX"; exit -1
+      - name: Load pool image from cache
+        run: docker load < /tmp/imgcache/img_libvcx.rar
+
+      - name: Verify images were loaded
+        run: |
+          docker image ls --format "{{.Repository}}:{{.Tag}}" | grep "$DOCKER_IMG_NAME_LIBVCX" || { echo "Image $DOCKER_IMG_NAME_LIBVCX was not found!"; docker image ls; exit 1; }
+
+      - name: Docker Login
+        uses: azure/docker-login@v1
+        with:
+          login-server: docker.pkg.github.com # TODO: Temporarily, publish to GPR
+          username: $GITHUB_ACTOR
+          password: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Publish image
+        run: |
+          REMOTE_DOCKER_IMG_NAME_LIBVCX="docker.pkg.github.com/$GITHUB_REPOSITORY_LOWERCASE/$DOCKER_IMG_NAME_LIBVCX"
+          docker tag "$DOCKER_IMG_NAME_LIBVCX" "$REMOTE_DOCKER_IMG_NAME_LIBVCX"
+          docker push "$REMOTE_DOCKER_IMG_NAME_LIBVCX" || true
