Tag docker images by cache key
Signed-off-by: Miroslav Kovar <miroslavkovar@protonmail.com>

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -12,10 +12,6 @@ jobs:
   workflow-setup:
     runs-on: ubuntu-latest
     outputs:
-      NODE_VER: ${{ steps.mainstep.outputs.NODE_VER }}
-      RUST_VER: ${{ steps.mainstep.outputs.RUST_VER }}
-      INDYSDK_REPO: ${{ steps.mainstep.outputs.INDYSDK_REPO }}
-      INDYSDK_REVISION: ${{ steps.mainstep.outputs.INDYSDK_REVISION }}
       LIBVCX_REVISION: ${{ steps.mainstep.outputs.LIBVCX_REVISION }}
       GITHUB_REPOSITORY_LOWERCASE: ${{ steps.mainstep.outputs.GITHUB_REPOSITORY_LOWERCASE }}
       CACHE_KEY_BASE: ${{ steps.mainstep.outputs.CACHE_KEY_BASE }}
@@ -28,17 +24,12 @@ jobs:
       DOCKER_IMG_NAME_AGENCY: ${{ steps.mainstep.outputs.DOCKER_IMG_NAME_AGENCY }}
       DOCKER_IMG_NAME_LIBVCX: ${{ steps.mainstep.outputs.DOCKER_IMG_NAME_LIBVCX }}
       RELEASE_VERSION: ${{ steps.mainstep.outputs.RELEASE_VERSION }}
-    env:
-      NODE_VER: "8.x"
-      RUST_VER: "1.43.1"
-      INDYSDK_REPO: "https://github.com/hyperledger/indy-sdk"
-      INDYSDK_REVISION: "1.15.0"
     steps:
       - name: Git checkout
         uses: actions/checkout@v1
       - uses: actions-rs/toolchain@v1
         with:
-          toolchain: ${{ env.RUST_VER }}
+          toolchain: 1.40.0
       - name: Set custom env variables
         run: |
           set -x
@@ -88,10 +79,18 @@ jobs:
           echo ::set-env name=DOCKER_TAG_VERSION::$(echo $DOCKER_TAG_VERSION)
 
           BASE_HASH="$(echo ${{ hashFiles('ci/base.dockerfile') }})"
+          LIBVCX_HASH="$(echo ${{ hashFiles('libvcx') }})-$(echo ${{ hashFiles('ci/libvcx.dockerfile') }})"
+          ANDROID_HASH="$(echo ${{ hashFiles('libvcx') }})-$(echo ${{ hashFiles('wrappers') }})-$(echo ${{ hashFiles('wrappers/java/ci/android.dockerfile') }})-$(echo $BASE_HASH)"
+          POOL_HASH="$(echo ${{ hashFiles('ci/indy-pool.dockerfile') }})"
           echo ::set-env name=BASE_HASH::$(echo $BASE_HASH)
-          echo ::set-env name=LIBVCX_HASH::"$(echo ${{ hashFiles('libvcx') }})-$(echo ${{ hashFiles('ci/libvcx.dockerfile') }})-$(echo $BASE_HASH)"
-          echo ::set-env name=ANDROID_HASH::"$(echo ${{ hashFiles('libvcx') }})-$(echo ${{ hashFiles('wrappers') }})-$(echo ${{ hashFiles('wrappers/java/ci/android.dockerfile') }})-$(echo $BASE_HASH)"
-          echo ::set-env name=POOL_HASH::$(echo ${{ hashFiles('ci/indy-pool.dockerfile') }})
+          echo ::set-env name=LIBVCX_HASH::$(echo $LIBVCX_HASH)
+          echo ::set-env name=ANDROID_HASH::$(echo $ANDROID_HASH)
+          echo ::set-env name=POOL_HASH::$(echo $POOL_HASH)
+
+          echo ::set-env name=CACHE_KEY_BASE::branch-$BRANCH_NAME-hash-$BASE_HASH
+          echo ::set-env name=CACHE_KEY_LIBVCX::branch-$BRANCH_NAME-hash-$LIBVCX_HASH
+          echo ::set-env name=CACHE_KEY_ANDROID::branch-$BRANCH_NAME-hash-$ANDROID_HASH
+          echo ::set-env name=CACHE_KEY_POOL::branch-$BRANCH_NAME-hash-$ANDROID_HASH
 
           DOCKER_IMG_NAME_AGENCY="docker.pkg.github.com/absaoss/vcxagencynode/vcxagency-node:0.1.0"
           echo ::set-env name=DOCKER_IMG_NAME_AGENCY::$(echo $DOCKER_IMG_NAME_AGENCY)
@@ -103,8 +102,6 @@ jobs:
           DOCKER_IMG_NAME_ANDROID="android-test"
           echo ::set-env name=DOCKER_IMG_NAME_ANDROID::$(echo $DOCKER_IMG_NAME_ANDROID)
 
-          echo ::set-env name=NODE_VER::$(echo $NODE_VER)
-          echo ::set-env name=RUST_VER::$(echo $RUST_VER)
           echo ::set-env name=RELEASE_VERSION::$(echo $RELEASE_VERSION)
 
       - name: Set and print outputs
@@ -112,23 +109,17 @@ jobs:
         run: |
           set -x
           echo "::set-output name=GITHUB_REPOSITORY_LOWERCASE::$GITHUB_REPOSITORY_LOWERCASE"
-          echo "::set-output name=NODE_VER::$NODE_VER"
-          echo "::set-output name=RUST_VER::$RUST_VER"
-          echo "::set-output name=INDYSDK_REPO::$INDYSDK_REPO"
-          echo "::set-output name=INDYSDK_REVISION::$INDYSDK_REVISION"
           echo "::set-output name=LIBVCX_REVISION::$DOCKER_TAG_VERSION"
-          echo "::set-output name=DOCKER_IMG_NAME_BASE::$DOCKER_IMG_NAME_BASE"
+          echo "::set-output name=CACHE_KEY_BASE::$CACHE_KEY_BASE"
+          echo "::set-output name=CACHE_KEY_LIBVCX::$CACHE_KEY_LIBVCX"
+          echo "::set-output name=CACHE_KEY_ANDROID::$CACHE_KEY_ANDROID"
+          echo "::set-output name=CACHE_KEY_POOL::$CACHE_KEY_POOL"
+          echo "::set-output name=DOCKER_IMG_NAME_BASE::$CACHE_KEY_BASE"
           echo "::set-output name=DOCKER_IMG_NAME_AGENCY::$DOCKER_IMG_NAME_AGENCY"
-          echo "::set-output name=DOCKER_IMG_NAME_ANDROID::$DOCKER_IMG_NAME_ANDROID"
-          echo "::set-output name=DOCKER_IMG_NAME_AGENCY::$DOCKER_IMG_NAME_AGENCY"
-          echo "::set-output name=DOCKER_IMG_NAME_LIBVCX::libvcx:$DOCKER_TAG_VERSION"
-          echo "::set-output name=DOCKER_IMG_NAME_POOL::indypool:$DOCKER_TAG_VERSION"
-          echo "::set-output name=CACHE_KEY_BASE::branch-$BRANCH_NAME-hash-$BASE_HASH"
-          echo "::set-output name=CACHE_KEY_LIBVCX::branch-$BRANCH_NAME-hash-$LIBVCX_HASH"
-          echo "::set-output name=CACHE_KEY_ANDROID::branch-$BRANCH_NAME-hash-$ANDROID_HASH"
-          echo "::set-output name=CACHE_KEY_POOL::branch-$BRANCH_NAME-hash-$POOL_HASH"
+          echo "::set-output name=DOCKER_IMG_NAME_ANDROID::$CACHE_KEY_ANDROID"
+          echo "::set-output name=DOCKER_IMG_NAME_LIBVCX::libvcx:$CACHE_KEY_LIBVCX"
+          echo "::set-output name=DOCKER_IMG_NAME_POOL::indypool:$CACHE_KEY_POOL"
           echo "::set-output name=RELEASE_VERSION::$RELEASE_VERSION"
-
 
   build-image-indypool:
     needs: workflow-setup
@@ -161,9 +152,7 @@ jobs:
           docker load < /tmp/imgcache/img_indypool.rar
       - name: Verify indypool image was loaded
         run: |
-          IFS=$':' read -a arr <<< $DOCKER_IMG_NAME_POOL
-          DOCKER_IMG_NAME_TAGLESS=${arr[0]}
-          docker image ls --format "{{.Repository}}" | grep "$DOCKER_IMG_NAME_TAGLESS" || { echo "Image $DOCKER_IMG_NAME_TAGLESS was not found!" ; exit 1; }
+          docker image ls --format "{{.Repository}}{{.Tag}}" | grep "$DOCKER_IMG_NAME_POOL" || { echo "Image $DOCKER_IMG_NAME_POOL was not found!" ; exit 1; }
 
   build-image-base:
     needs: workflow-setup
@@ -196,11 +185,9 @@ jobs:
       - name: Load base image from cache
         run: |
           docker load < /tmp/imgcache/img_base.rar
-      - name: Verify libvcx image was loaded
+      - name: Verify base image was loaded
         run: |
-          IFS=$':' read -a arr <<< $DOCKER_IMG_NAME_BASE
-          DOCKER_IMG_NAME_TAGLESS=${arr[0]}
-          docker image ls --format "{{.Repository}}" | grep "$DOCKER_IMG_NAME_TAGLESS" || { echo "Image $DOCKER_IMG_NAME_TAGLESS was not found!" ; exit 1; }
+          docker image ls --format "{{.Repository}}{{.Tag}}" | grep "$DOCKER_IMG_NAME_BASE" || { echo "Image $DOCKER_IMG_NAME_BASE was not found!" ; exit 1; }
 
   build-image-libvcx:
     needs: [workflow-setup, build-image-base]
@@ -213,10 +200,6 @@ jobs:
           echo ::set-env name=CACHE_KEY_BASE::$(echo ${{needs.workflow-setup.outputs.CACHE_KEY_BASE}})
           echo ::set-env name=CACHE_KEY_LIBVCX::$(echo ${{needs.workflow-setup.outputs.CACHE_KEY_LIBVCX}})
           echo ::set-env name=DOCKER_IMG_NAME_LIBVCX::$(echo ${{needs.workflow-setup.outputs.DOCKER_IMG_NAME_LIBVCX}})
-          echo ::set-env name=RUST_VER::$(echo ${{needs.workflow-setup.outputs.RUST_VER}})
-          echo ::set-env name=NODE_VER::$(echo ${{needs.workflow-setup.outputs.NODE_VER}})
-          echo ::set-env name=INDYSDK_REPO::$(echo ${{needs.workflow-setup.outputs.INDYSDK_REPO}})
-          echo ::set-env name=INDYSDK_REVISION::$(echo ${{needs.workflow-setup.outputs.INDYSDK_REVISION}})
       - name: Git checkout
         uses: actions/checkout@v2
       - name: Try load base image from cache.
@@ -240,11 +223,7 @@ jobs:
         if: steps.cache-image-libvcx.outputs.cache-hit != 'true'
         run: |
           set -x
-          docker build --build-arg "INDYSDK_REPO=$INDYSDK_REPO" \
-                       --build-arg "INDYSDK_REVISION=v$INDYSDK_REVISION" \
-                       --build-arg "RUST_VER=$RUST_VER" \
-                       --build-arg "NODE_VER=$NODE_VER" \
-                       --build-arg "NPMJS_TOKEN=$NPMJS_TOKEN" \
+          docker build --build-arg "NPMJS_TOKEN=$NPMJS_TOKEN" \
                        --build-arg "USER_ID=$UID" \
                        -f ci/libvcx.dockerfile \
                        -t "$DOCKER_IMG_NAME_LIBVCX" \
@@ -257,9 +236,7 @@ jobs:
           docker load < /tmp/imgcache/img_libvcx.rar
       - name: Verify libvcx image was loaded
         run: |
-          IFS=$':' read -a arr <<< $DOCKER_IMG_NAME_LIBVCX
-          DOCKER_IMG_NAME_TAGLESS=${arr[0]}
-          docker image ls --format "{{.Repository}}" | grep "$DOCKER_IMG_NAME_TAGLESS" || { echo "Image $DOCKER_IMG_NAME_TAGLESS was not found!" ; exit 1; }
+          docker image ls --format "{{.Repository}}{{.Tag}}" | grep "$DOCKER_IMG_NAME_LIBVCX" || { echo "Image $DOCKER_IMG_NAME_LIBVCX was not found!" ; exit 1; }
 
   build-image-android:
     needs: [workflow-setup, build-image-base]
@@ -273,9 +250,6 @@ jobs:
           echo ::set-env name=CACHE_KEY_ANDROID::$(echo ${{needs.workflow-setup.outputs.CACHE_KEY_ANDROID}})
           echo ::set-env name=DOCKER_IMG_NAME_ANDROID::$(echo ${{needs.workflow-setup.outputs.DOCKER_IMG_NAME_ANDROID}})
           echo ::set-env name=LIBVCX_REVISION::$(echo ${{needs.workflow-setup.outputs.LIBVCX_REVISION}})
-          echo ::set-env name=INDYSDK_REVISION::$(echo ${{needs.workflow-setup.outputs.INDYSDK_REVISION}})
-          echo ::set-env name=LIBVCX_REVISION::$(echo ${{needs.workflow-setup.outputs.LIBVCX_REVISION}})
-          echo ::set-env name=RUST_VER::$(echo ${{needs.workflow-setup.outputs.RUST_VER}})
       - name: Git checkout
         uses: actions/checkout@v2
       - name: Try loading base image from cache.
@@ -299,11 +273,7 @@ jobs:
       - name: If NOT found in cache, build and cache image.
         if: steps.cache-image-android.outputs.cache-hit != 'true'
         run: |
-          docker build --build-arg "RUST_VER=$RUST_VER" \
-                       --build-arg "JAVA_VER=8" \
-                       --build-arg "LIBVCX_VER=$LIBVCX_REVISION" \
-                       --build-arg "INDY_VER=$INDYSDK_REVISION" \
-                       -f wrappers/java/ci/android.dockerfile \
+          docker build -f wrappers/java/ci/android.dockerfile \
                        -t "$DOCKER_IMG_NAME_ANDROID" \
                         .
           mkdir -p /tmp/imgcache
@@ -314,9 +284,7 @@ jobs:
           docker load < /tmp/imgcache/img_android.rar
       - name: Verify android image was loaded
         run: |
-          IFS=$':' read -a arr <<< $DOCKER_IMG_NAME_ANDROID
-          DOCKER_IMG_NAME_TAGLESS=${arr[0]}
-          docker image ls --format "{{.Repository}}" | grep "$DOCKER_IMG_NAME_TAGLESS" || { echo "Image $DOCKER_IMG_NAME_TAGLESS was not found!" ; exit 1; }
+          docker image ls --format "{{.Repository}}{{.Tag}}" | grep "$DOCKER_IMG_NAME_ANDROID" || { echo "Image $DOCKER_IMG_NAME_ANDROID was not found!" ; exit 1; }
 
   test-libvcx-image:
     runs-on: ubuntu-16.04
@@ -589,9 +557,7 @@ jobs:
 
       - name: Verify libvcx image were loaded
         run: |
-          IFS=$':' read -a arr <<< $DOCKER_IMG_NAME_LIBVCX
-          DOCKER_IMG_NAME_TAGLESS=${arr[0]}
-          docker image ls --format "{{.Repository}}" | grep "$DOCKER_IMG_NAME_TAGLESS" || { echo "Image $DOCKER_IMG_NAME_TAGLESS was not found!" ; exit 1; }
+          docker image ls --format "{{.Repository}}{{.Tag}}" | grep "$DOCKER_IMG_NAME_LIBVCX" || { echo "Image $DOCKER_IMG_NAME_LIBVCX was not found!" ; exit 1; }
 
       - name: Docker Login
         uses: azure/docker-login@v1
@@ -604,8 +570,10 @@ jobs:
         run: |
           if [[ "$RELEASE_VERSION" ]]
           then
-            echo "Releasing libvcx docker image version $RELEASE_VERSION..."
-            REMOTE_DOCKER_IMG_NAME_LIBVCX="docker.pkg.github.com/$GITHUB_REPOSITORY_LOWERCASE/$DOCKER_IMG_NAME_LIBVCX"
+            IFS=$':' read -a arr <<< $DOCKER_IMG_NAME_LIBVCX
+            DOCKER_IMG_NAME_TAGLESS=${arr[0]}
+            REMOTE_DOCKER_IMG_NAME_LIBVCX="docker.pkg.github.com/${GITHUB_REPOSITORY_LOWERCASE}/${DOCKER_IMG_NAME_TAGLESS}:${RELEASE_VERSION}"
+            echo "Releasing libvcx docker image version $RELEASE_VERSION, tagged $REMOTE_DOCKER_IMG_NAME_LIBVCX"
             docker tag "$DOCKER_IMG_NAME_LIBVCX" "$REMOTE_DOCKER_IMG_NAME_LIBVCX"
             docker push "$REMOTE_DOCKER_IMG_NAME_LIBVCX" || true
           else
@@ -640,9 +608,7 @@ jobs:
 
       - name: Verify libvcx image were loaded
         run: |
-          IFS=$':' read -a arr <<< $DOCKER_IMG_NAME_LIBVCX
-          DOCKER_IMG_NAME_TAGLESS=${arr[0]}
-          docker image ls --format "{{.Repository}}" | grep "$DOCKER_IMG_NAME_TAGLESS" || { echo "Image $DOCKER_IMG_NAME_TAGLESS was not found!" ; exit 1; }
+          docker image ls --format "{{.Repository}}{{.Tag}}" | grep "$DOCKER_IMG_NAME_LIBVCX" || { echo "Image $DOCKER_IMG_NAME_LIBVCX was not found!" ; exit 1; }
 
       - name: Docker Login
         uses: azure/docker-login@v1
