Add agent-core npmjs publishing
Signed-off-by: Patrik Stas <patrik.stas@absa.africa>

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -925,6 +925,56 @@ jobs:
              echo "New version was not defined, skipping release."
           fi
 
+  publish-agent-core:
+    runs-on: ubuntu-16.04
+    needs: [workflow-setup, build-image-indypool, build-image-libvcx, test-libvcx-image-general_test, test-libvcx-image-pool_tests, test-libvcx-image-agency_pool_tests, test-node-wrapper, test-integration-node-wrapper]
+    env:
+      NPMJS_TOKEN: ${{ secrets.NPMJS_TOKEN }}
+    steps:
+      - name: Load env. variables
+        run: |
+          echo ::set-env name=CACHE_KEY_LIBVCX::$(echo ${{needs.workflow-setup.outputs.CACHE_KEY_LIBVCX}})
+          echo ::set-env name=DOCKER_IMG_NAME_LIBVCX::$(echo ${{needs.workflow-setup.outputs.DOCKER_IMG_NAME_LIBVCX}})
+          echo ::set-env name=PUBLISH_VERSION::$(echo ${{needs.workflow-setup.outputs.PUBLISH_VERSION}})
+      - name: Git checkout
+        uses: actions/checkout@v2
+
+      - name: Load libvcx image cache
+        id: load-cached-libvcx-image
+        uses: actions/cache@v2
+        with:
+          path: /tmp/imgcache
+          key: ${{ env.CACHE_KEY_LIBVCX }}
+      - name: If no cached image found
+        if: steps.load-cached-libvcx-image.outputs.cache-hit != 'true'
+        run: echo "ERROR == Expected to find image from cache $CACHE_KEY_LIBVCX"; exit -1
+      - name: Load image from cache
+        run: docker load < /tmp/imgcache/img_libvcx.rar
+
+      - name: Verify libvcx image were loaded
+        run: |
+          docker image ls --format "{{.Repository}}:{{.Tag}}" | grep "$DOCKER_IMG_NAME_LIBVCX" || { echo "Image $DOCKER_IMG_NAME_LIBVCX was not found!" ; exit 1; }
+
+      - name: Docker Login
+        uses: azure/docker-login@v1
+        with:
+          login-server: docker.pkg.github.com
+          username: $GITHUB_ACTOR
+          password: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Release agent-core package
+        run: |
+          if [[ "$PUBLISH_VERSION" ]]
+          then
+            echo "Releasing node wrapper version $PUBLISH_VERSION..."
+            docker run --rm -i --name libvcx --network host \
+                   -e NPMJS_TOKEN="$NPMJS_TOKEN" \
+                   -e PUBLISH_VERSION="$PUBLISH_VERSION" \
+                    "$DOCKER_IMG_NAME_LIBVCX" bash -c '$HOME/agents/node/vcxagent-core/publish.sh'
+          else
+             echo "New version was not defined, skipping release."
+          fi
+
   make-release:
     runs-on: ubuntu-16.04
     needs: [workflow-setup, build-image-indypool, build-image-libvcx, build-image-android, publish-ios-wrapper, publish-android-wrapper-device, publish-android-wrapper-emulator, test-libvcx-image-general_test, test-libvcx-image-pool_tests, test-libvcx-image-agency_pool_tests, test-android-build, test-node-wrapper, test-integration-node-wrapper]
